"""`verify.py` against a real thread, not a constructed one.

Everything in `test_verify.py` and `test_extract_runner.py` runs against
synthetic strings with hand-computed segments — and one of those had an
off-by-one that took computing the spans to find. This runs the same code
against a thread somebody actually posted: six documents, twenty segments, ten
substitutions spread across more than one comment, a deleted body, and a run of
seven full blocks in a single document.

Both failure modes `judge/CLAUDE.md` warns about live exactly here. A map that
fails on everything is loud and easy. **A map that silently passes against the
wrong text is the one this file exists for**, which is why the assertions below
check what a span RESOLVES TO rather than that it resolved.

The fixture is generated by `fixtures/threads/build.py`. Regenerating it is a
deliberate act, and this suite is what says whether the regenerated one is
still correct.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from judge.extract.schema import ExtractedClaim
from judge.extract.verify import OffsetMapping, Rejection, VerifiedQuote, verify

FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "threads" / "thread-1u1b22l.json"


@pytest.fixture(scope="module")
def thread() -> dict:
    if not FIXTURE.exists():  # pragma: no cover
        pytest.fail(
            f"{FIXTURE.name} is missing. Regenerate with "
            "`python fixtures/threads/build.py` — it is derived from a stored "
            "Reddit payload and needs no network."
        )
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def offsets(thread) -> list[OffsetMapping]:
    return [OffsetMapping(**s) for s in thread["offset_map"]]


def claim_for(thread, start: int, end: int, document_id: str) -> ExtractedClaim:
    """A claim quoting an exact span of the flattened text."""
    return ExtractedClaim.model_validate(
        {
            "source_comment_id": document_id,
            "model_ref": {
                "surface": "gemini",
                "resolved_version_id": "google/gemini-2.5-flash",
                "specificity": "family",
                "resolution_confidence": 0.7,
            },
            "capability": "summarization.fidelity",
            "polarity": "negative",
            "quote": thread["flattened_text"][start:end],
            "quote_offset": [start, end],
            "relevance": "central",
        }
    )


class TestTheFixtureItself:
    def test_it_carries_the_shapes_it_was_built_for(self, thread):
        """A fixture that lost its hard cases tests less than it looks like.

        The first build selected six documents with one substitution between
        them, because the forced pick asked for "any substituted character" and
        found U+2588 before it found an emoji.
        """
        segments = thread["offset_map"]
        substitutions = [
            s
            for s in segments
            if (s["flat_end"] - s["flat_start"]) != (s["raw_end"] - s["raw_start"])
        ]
        documents_with_substitutions = {s["document_id"] for s in substitutions}

        assert len(thread["member_document_ids"]) >= 4
        assert len(substitutions) >= 5
        assert len(documents_with_substitutions) >= 2, (
            "substitutions in one document only: a constant per-document delta "
            "would pass, which is the bug this fixture exists to catch"
        )
        assert any(
            body in ("[deleted]", "[removed]") for body in thread["raw_text_of"].values()
        ), "no absent body — a different offset problem from a substituted one"

    def test_every_identity_segment_maps_the_same_number_of_characters(self, thread):
        """The map's own invariant, checked against the map rather than assumed.

        Content is deliberately NOT compared. A no-break space normalising to a
        space is one character for one, so the segment stays identity-length
        while the characters differ — positionally correct and content-differing
        at once, which is the state a length check confirms and an equality
        check would wrongly reject.
        """
        for s in thread["offset_map"]:
            flat_len = s["flat_end"] - s["flat_start"]
            raw_len = s["raw_end"] - s["raw_start"]
            assert flat_len == raw_len or raw_len == 1, (
                f"segment in {s['document_id']} is neither identity-length nor a "
                f"single-character substitution: {flat_len} flat, {raw_len} raw"
            )

    def test_segments_are_contiguous_and_ordered_within_a_document(self, thread):
        by_document: dict[str, list[dict]] = {}
        for s in thread["offset_map"]:
            by_document.setdefault(s["document_id"], []).append(s)

        for document_id, segments in by_document.items():
            for earlier, later in zip(segments, segments[1:], strict=False):
                assert earlier["flat_end"] == later["flat_start"], document_id
                assert earlier["raw_end"] == later["raw_start"], document_id


class TestVerificationAgainstRealText:
    def test_a_span_in_the_root_resolves_to_the_root(self, thread, offsets):
        root_id = thread["thread_root_id"]
        first = next(s for s in thread["offset_map"] if s["document_id"] == root_id)
        start = first["flat_start"] + 5
        end = start + 20

        outcome = verify(
            claim_for(thread, start, end, root_id),
            flattened_text=thread["flattened_text"],
            offset_map=offsets,
            raw_text_of=thread["raw_text_of"],
        )
        assert isinstance(outcome, VerifiedQuote)
        assert outcome.document_id == root_id

    def test_a_span_after_a_substitution_resolves_to_the_right_document(
        self, thread, offsets
    ):
        """The case that broke it the first time.

        Under a constant per-document delta this either lands past the end of
        the raw text or, worse, inside the wrong document — and the second
        fails silently, producing a quote attributed to somebody who never
        wrote it.
        """
        substitution = next(
            s
            for s in thread["offset_map"]
            if (s["flat_end"] - s["flat_start"]) != (s["raw_end"] - s["raw_start"])
        )
        following = next(
            s
            for s in thread["offset_map"]
            if s["document_id"] == substitution["document_id"]
            and s["flat_start"] >= substitution["flat_end"]
            and s["flat_end"] - s["flat_start"] > 12
        )
        start = following["flat_start"] + 2
        end = start + 10

        outcome = verify(
            claim_for(thread, start, end, substitution["document_id"]),
            flattened_text=thread["flattened_text"],
            offset_map=offsets,
            raw_text_of=thread["raw_text_of"],
        )
        assert isinstance(outcome, VerifiedQuote), outcome
        assert outcome.document_id == substitution["document_id"]

    def test_every_document_can_be_quoted(self, thread, offsets):
        """Not one span — every document in the thread.

        A map correct for the first document and wrong for the fifth is the
        realistic failure, and a single-span test would pass through it.
        """
        for document_id in thread["member_document_ids"]:
            segment = max(
                (s for s in thread["offset_map"] if s["document_id"] == document_id),
                key=lambda s: s["flat_end"] - s["flat_start"],
            )
            if segment["flat_end"] - segment["flat_start"] < 12:
                continue
            start = segment["flat_start"] + 1
            end = start + 10

            outcome = verify(
                claim_for(thread, start, end, document_id),
                flattened_text=thread["flattened_text"],
                offset_map=offsets,
                raw_text_of=thread["raw_text_of"],
            )
            assert isinstance(outcome, VerifiedQuote), f"{document_id}: {outcome}"
            assert outcome.document_id == document_id

    def test_a_fabricated_quote_still_fails_against_real_text(self, thread, offsets):
        """The guarantee, on a document large enough to hide in.

        2,481 characters of real prose is where a plausible invention is most
        likely to accidentally match something. It does not.
        """
        claim = claim_for(thread, 10, 40, thread["thread_root_id"])
        fabricated = claim.model_copy(
            update={"quote": "the model dropped every clause we cared about"}
        )

        outcome = verify(
            fabricated,
            flattened_text=thread["flattened_text"],
            offset_map=offsets,
            raw_text_of=thread["raw_text_of"],
        )
        assert isinstance(outcome, Rejection)

    def test_a_span_crossing_the_document_separator_is_refused(self, thread, offsets):
        """A quote spanning two comments has two authors and belongs to neither.

        The separator is not covered by any segment, so a span crossing it
        cannot resolve — and must not, because an unattributable quote cannot
        be displayed or counted.
        """
        boundary = next(
            (
                (earlier, later)
                for earlier, later in zip(
                    thread["offset_map"], thread["offset_map"][1:], strict=False
                )
                if earlier["document_id"] != later["document_id"]
            ),
            None,
        )
        assert boundary is not None, "fixture has only one document"
        earlier, later = boundary
        start = earlier["flat_end"] - 5
        end = later["flat_start"] + 5

        outcome = verify(
            claim_for(thread, start, end, earlier["document_id"]),
            flattened_text=thread["flattened_text"],
            offset_map=offsets,
            raw_text_of=thread["raw_text_of"],
        )
        assert isinstance(outcome, Rejection), (
            "a span crossing two documents resolved to one of them — that is "
            "the silent-wrong-attribution failure, not the loud one"
        )
